.\" Copyright (C) 2007 Emanuele Rocca
.TH XFCE4-AUTOSTART-EDITOR "1" "January 2007" "xfce4-autostart-editor" "User Commands"
.SH NAME
xfce4-autostart-editor \- XFce 4 Autostart Editor
.SH SYNOPSIS
.B xfce4-autostart-editor
.SH DESCRIPTION
.PP
Starts the XFce 4 Autostart Editor, which allows to edit the list of
autostarted applications.
.SH SEE ALSO
Upstream documentation in /usr/share/xfce4/doc/C/xfce4-session.html
.SH COPYRIGHT
Copyright \(co 2007 Emanuele Rocca
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

