.\" Copyright (C) 2007 Emanuele Rocca
.TH XFCE4-TIPS "1" "January 2007" "xfce4-tips" "User Commands"
.SH NAME
xfce4-tips \- XFce 4 Tips
.SH SYNOPSIS
.B xfce4-tips
.SH DESCRIPTION
.PP
This command displays some usage tips about XFce.
.SH FILES
.TP
.I /usr/share/xfce4/tips/tips
List of tips.
.SH SEE ALSO
Upstream documentation in /usr/share/xfce4/doc/C/index.html
.SH COPYRIGHT
Copyright \(co 2007 Emanuele Rocca
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

